### ISSUE TITLE
doesn't show up in Extensions menu

### ISSUE THREAD

**Issue by brynnd** [shlomif/Bezier-Envelope-for-Inkscape#1]
Hello,
I realize there's a newer version of this extension (a fork) (author: lemasney), but that account doesn't have any Issues tab, so I don't know how to contact the author.  I'm trying to install this in version 0.92 (or 0.91) but unzipped into extensions directory, it doesn't show up in Extensions menu.

Does it work, or can it be made to work?

Thank you very much,
brynn

**Comment by shlomif** [comment]
Hi @brynnd ! It seems to be fine here under "Extensions → Modify Path → Bezier Envelope". Can you find it there?

**Comment by shlomif** [comment]
Closing per the IRC discussion and the README mod.
