### ISSUE TITLE
Getting message not able to use

### ISSUE THREAD

**Issue by vegandarwin** [shlomif/Bezier-Envelope-for-Inkscape#4]
Not sure where to post this question. I am getting this not error message when i select the bezier envelope extention

  File "bezierenvelope.py", line 381, in <module>
    e.affect()
  File "inkex.py", line 283, in affect
    self.effect()
  File "bezierenvelope.py", line 90, in effect
    raise Exception, "Both letter and envelope must be SVG paths."
Exception: Both letter and envelope must be SVG paths.
I did convert the text and box into paths then saved as SVG ropened the file select the text then box this is what pops up?  Im not that experienced at this so im assuming im doing something wrong ?

**Comment by shlomif** [comment]
Hi @vegandarwin ! Please see https://github.com/shlomif/writing-the-perfect-question and provide more details: OS, inkscape version, python version, a sample test case + reproduction script/etc. Also see https://github.com/shlomif/how-to-share-code-online .

**Comment by shlomif** [comment]
Closing as stale. Can reopen if needed/
