### ISSUE TITLE
Not compatible with Inkscape 1.0

### ISSUE THREAD

**Issue by bwruehl** [shlomif/Bezier-Envelope-for-Inkscape#5]
Since this is the only location that I see this extension posted, and several users have noted having an issue, I am unsure where else to pose this question/issue.

The current posted version (posted on Apr 2, 2016) is not compatible with Inkscape 1.0 on all OS platforms. Are there any plans to update this version or is this project now defunct?

**Comment by shlomif** [comment]
@bwruehl : thanks for reporting this. I'll try to look into fixing it, hopefully soon, despite the fact that I didn't originate this extension. https://shlomif-tech.livejournal.com/37969.html . In the meanwhile, patches / pull-reqs would be welcome too.

**Comment by shlomif** [comment]
@bwruehl : hi, please do a `git pull` and try again.

**Comment by bwruehl** [comment]
Sorry for the delay in response, I wanted to try and test my own issues
before replying. First of all, thank you for putting effort towards
attempting to update this extension even though you are not the original
owner. Many of the graphics people out there appreciate the effort. I did
attempt your updated files but it appears that it does not work and
intended. While I do not get an error, the output vector is severely
altered in a way it no where near resembles the desired output.

To be specific on my testings, I am running Ubuntu 20.04 on 4 different
machines, two have Inkscape version 1.0 and two have version .92.5. The
original bezier envelope extension files work fine with .92.5 but create
errors on 1.0. The new files error out on version .92.5 but create a
completely abstract output in version 1.0. I have attached two images to
this email, one being the desired output which I captured from Inkscape
.92.5 with the old extension files and the other from Inkscape 1.0 with
your recently modified extension files.

While I am not a coder / programer, I would be glad to help out on this in
any way that I can as this is/was one of the extensions I used very often.

Thanks

**Comment by shlomif** [comment]
@bwruehl : hi! I didn't receive your attachments. Can you use the github web interface or send them to shlomif@gmail.com ?

**Comment by bwruehl** [comment]
Here are the images that did not get passed in the email.
[
![bezier broke](https://user-images.githubusercontent.com/47705235/90626718-505b1f00-e1e9-11ea-8363-60a79374f44b.png)
![bezier correct](https://user-images.githubusercontent.com/47705235/90626736-53eea600-e1e9-11ea-8757-c41c8385cc0b.png)
](url)

**Comment by shlomif** [comment]
@bwruehl : hi! can you also provide the input sources? See: https://github.com/shlomif/writing-the-perfect-question

**Comment by bwruehl** [comment]
I am not sure what you are looking for when you ask for the input sources so I will provide what I am using to test. I have created a test svg file that has nothing in it but text that has been converted to a path (vectored) and a 4 point shape. I will send you the svg in email as it won't let me attach it in this post. I select the text, then the shape, then go to  Extensions -> Modify Path -> Bezier Envelope. It should then convert the text shape to match that of the 4 point shape as seen in the images I provided.

Here is a good link with videos that show how this is supposed to work: https://cleversomeday.com/textwarpink/

**Comment by shlomif** [comment]
> I am not sure what you are looking for when you ask for the input sources so I will provide what I am using to test. I have created a test svg file that has nothing in it but text that has been converted to a path (vectored) and a 4 point shape. I will send you the svg in email as it won't let me attach it in this post. I select the text, then the shape, then go to Extensions -> Modify Path -> Bezier Envelope. It should then convert the text shape to match that of the 4 point shape as seen in the images I provided.
> 
> Here is a good link with videos that show how this is supposed to work: https://cleversomeday.com/textwarpink/

Thanks again! I got the input svg and uploaded it to https://www.shlomifish.org/Files/files/images/bezier-envelope-for-inkscape--extension--bwruehl-test-1.svg .

**Comment by ghost** [comment]
You can use path > path effect > envelop deformation instead as well.
https://www.youtube.com/watch?v=l3BHcregNUs

**Comment by dpanderson1960** [comment]
I really liked the results I attained with this extension, but have now migrated to Inkscape 1.1.  Any chance this extension could be fixed up to work with 1.1?

TIA

**Comment by shlomif** [comment]
Hi,

On Tue, 08 Jun 2021 14:21:50 -0700
dpanderson1960 ***@***.***> wrote:

> I really liked the results I attained with this extension, but have now
> migrated to Inkscape 1.1.  Any chance this extension could be fixed up to
> work with 1.1?
> 

I've been meaning to look into that, but have been distracted by higher
priorities:

*
https://github.com/shlomif/shlomif-tech-diary/blob/master/why-the-so-called-real-world-i-am-trapped-in-makes-little-sense--2020-05-19.asciidoc

* https://www.shlomifish.org/humour/Queen-Padme-Tales/

In the meanwhile, merge requests / real forks are encouraged.


> TIA
> 



-- 

Shlomi Fish       https://www.shlomifish.org/
https://www.shlomifish.org/open-source/resources/tech-tips/

Chuck Norris read the entire English Wikipedia in 24 hours. Twice.
    — https://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by shlomif** [comment]
hi all! Does this still happen with Inkscape 1.1.x? https://github.com/shlomif/Shlomi-Fish-Back-to-my-Homepage-Logo seems to work fine for me. Also see https://github.com/shlomif/writing-the-perfect-question .

**Comment by dpanderson1960** [comment]
I am now running 1.1.1 and it seems to work fine.  Thank you!

**Comment by shlomif** [comment]
> I am now running 1.1.1 and it seems to work fine. Thank you!

thanks @dpanderson1960 ! I'm closing this issue for now to avoid clutter. I can reopen it.
