### ISSUE TITLE
Path to copy extension in Mac OS

### ISSUE THREAD

**Issue by wra1w0** [shlomif/Bezier-Envelope-for-Inkscape#9]
In Mac, you need a different path (`/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions`) to install the extension. 
```bash
cp -f bezierenvelope.inx bezierenvelope.py /Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions
```
Can you add this to instructions in README? 

`make install` also don't work for Mac because of wrong path.

P.S.:
Is it not simpler instead of Makefile just to write this copy commands in README (In Mac you need to install dev tools to run Makefiles. Not everyone need it)?  
For example:

**Linux:**
```bash
cp -f bezierenvelope.inx bezierenvelope.py ~/.config/inkscape/extensions/
```

**Mac:**
```bash
cp -f bezierenvelope.inx bezierenvelope.py /Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions
```

**Comment by shlomif** [comment]
@rmnwnsx : I now use `mkdir -p` to mkdir the dot config dir. I prefer having a build system and may end up using cmake or similar here too eventually: https://github.com/shlomif/Freenode-programming-channel-FAQ/blob/master/FAQ_with_ToC__generated.md#what-are-some-best-practices-in-programming-that-i-should-adopt .

**Comment by shlomif** [comment]
closing for now.
